const Identity = {
    IDENTITY_FIRST_NAME: 'IDENTITY_FIRST_NAME',
    IDENTITY_LAST_NAME: 'IDENTITY_LAST_NAME',
    IDENTITY_GENDER: 'IDENTITY_GENDER',
    IDENTITY_DOB_MONTH: 'IDENTITY_DOB_MONTH',
    IDENTITY_DOB_DATE: 'IDENTITY_DOB_DATE',
    IDENTITY_DOB_YEAR: 'IDENTITY_DOB_YEAR',
    IDENTITY_USER_NAME: 'IDENTITY_USER_NAME',
    IDENTITY_COUNTRY: 'IDENTITY_COUNTRY',
    IDENTITY_PASSWORD: 'IDENTITY_PASSWORD',
    IDENTITY_APP_NAME: 'IDENTITY_APP_NAME'
}

const RandomIdentity = {
    IDENTITY_FIRST_NAME: 'RANDOM_IDENTITY_FIRST_NAME',
    IDENTITY_LAST_NAME: 'RANDOM_IDENTITY_LAST_NAME',
    IDENTITY_GENDER: 'RANDOM_IDENTITY_GENDER',
    IDENTITY_DOB_MONTH: 'RANDOM_IDENTITY_DOB_MONTH',
    IDENTITY_DOB_DATE: 'RANDOM_IDENTITY_DOB_DATE',
    IDENTITY_DOB_YEAR: 'RANDOM_IDENTITY_DOB_YEAR',
    IDENTITY_USER_NAME: 'RANDOM_IDENTITY_USER_NAME',
    IDENTITY_COUNTRY: 'RANDOM_IDENTITY_COUNTRY',
    IDENTITY_PASSWORD: 'RANDOM_IDENTITY_PASSWORD',
    IDENTITY_APP_NAME: 'RANDOM_IDENTITY_APP_NAME'
}

const Actions = {
    ACTION_TYPE_GOTO: 'goto',
    ACTION_TYPE_SET_VIEWPORT: 'setviewport',
    ACTION_TYPE_INPUT: 'input',
    ACTION_TYPE_CLICK: 'click',
    ACTION_TYPE_SELECT: 'select',
    ACTION_TYPE_SLEEP: 'sleep',
    ACTION_TYPE_OUTPUT: 'output',
    ACTION_TYPE_EVALUATE: 'evaluate',
    ACTION_TYPE_NAVIGATION: 'navigation',
    ACTION_TYPE_CONDITION: 'condition',
    ACTION_TYPE_MOUSE_DOWN: 'mousedown',
    ACTION_TYPE_MOUSE_UP: 'mouseup',
    ACTION_TYPE_MOUSE_MOVE: 'mousemove',
    ACTION_TYPE_MOUSE_CLICK: 'mouseclick',
    ACTION_TYPE_KEY_PRESS: 'keypress',
    ACTION_TYPE_TYPE_TEXT: 'typeText',
    ACTION_TYPE_KEY_UP: 'keyup',
    ACTION_TYPE_KEY_DOWN: 'keydown',
    ACTION_TYPE_SETUP_RANDOM_INDENTITY: 'randomIdentity',
    ACTION_TYPE_ENABLE_PROXY: 'proxy',
    ACTION_TYPE_REMOTE_JAVASCRIPT: 'remoteJs',
    ACTION_TYPE_SOLVE_CAPTCHA: 'captcha',
    ACTION_TYPE_WRITE_DATA_INTO_COLLECTION: 'writeDataIntoCollection',
    ACTION_TYPE_TOKEN: 'token',
}

const Collections = {
    COLLECTION_WORKERS: 'workers',
    COLLECTION_LOGS: 'logs',
    COLLECTION_PROTOCOLS: 'protocols',
    COLLECTION_TASKS: 'tasks',
    COLLECTION_WORKS: 'works',
    COLLECTION_OVERRIDE: 'override',
    COLLECTION_WORK_HSITORY: 'work-history'
}

const Variables = {
    TOKEN: 'TOKEN',
    IS_REDIRECTED: 'isRedirected',
    IS_OVERRIDDEN: 'isOverridden',
    STORE_SS: 'storeSS',
    SS_COUNT: 'ssCount',
}

const Countries = ['Australia', 'Thailand', 'Indonesia', 'Somalia', 'United Kingdom', 'South Africa', 'Guinea', 'Bangladesh', 'India', 'Mongolia', "Nigeria", 'Russia', 'Ukraine', 'Vietnam', 'Nepal', 'Myanmar', 'United States', 'Brazil', 'Chile', 'Argentina', 'France', 'Ireland', 'Mexico', 'Peru', 'Mauritius', 'Taiwan', 'Poland', 'Hungary', 'Germany', 'Turkey', 'Spain', 'Italy'];

const CountryCodes = {
    "Albania": "AL",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Bangladesh": "BD",
    "Bolivia": "BO",
    "Brazil": "BR",
    "Bulgaria": "BG",
    "Cambodia": "KH",
    "Canada": "CA",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Czechia": "CZ",
    "Democratic Republic Of Timor Leste": "TL",
    "Ecuador": "EC",
    "Fiji": "FJ",
    "Germany": "DE",
    "Ghana": "GH",
    "Guadeloupe": "GP",
    "Guinea": "GN",
    "Honduras": "HN",
    "Hungary": "HU",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Japan": "JA",
    "Kazakhstan": "KZ",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Mongolia": "MN",
    "Myanmar": "MM",
    "Nepal": "NP",
    "Netherlands": "NL",
    "Nigeria": "NG",
    "Pakistan": "PK",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Puerto Rico": "PR",
    "Republic Of Korea": "KP",
    "Republic Of Moldova": "MD",
    "Romania": "RO",
    "Russia": "RU",
    "Serbia": "RS",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Somalia": "SO",
    "South Africa": "ZA",
    "Spain": "ES",
    "Syria": "SY",
    "Taiwan": "TW",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Turkey": "TR",
    "Ukraine": "UA",
    "United Kingdom": "GB",
    "United States": "US",
    "Venezuela": "VE",
    "Vietnam": "VN"
}

module.exports = {
    Identity,
    RandomIdentity,
    CountryCodes,
    Countries,
    Actions,
    Collections,
    Variables
}